services:
  postgres:
    image: bitnami/postgresql:15.7.0
    environment:
      - POSTGRESQL_DATABASE=rails_project_development
      - POSTGRESQL_USERNAME=rails_project
      - POSTGRESQL_PASSWORD=rails_project
      - POSTGRESQL_POSTGRES_PASSWORD=postgres # Default superuser password
    ports:
      - "5432:5432" 